"""Initial Registry Creation

Revision ID: 362b00c5364f
Revises: 
Create Date: 2026-02-19 07:42:40.554325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '362b00c5364f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medical_records', sa.Column('patient_portion', sa.Float(), nullable=False))
    op.add_column('medical_records', sa.Column('insurance_portion', sa.Float(), nullable=False))
    op.alter_column('medical_records', 'hospital_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('medical_records', 'doctor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index('idx_nin_timestamp', 'medical_records', ['patient_nin', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_nin_timestamp', table_name='medical_records')
    op.alter_column('medical_records', 'doctor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('medical_records', 'hospital_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('medical_records', 'insurance_portion')
    op.drop_column('medical_records', 'patient_portion')
    # ### end Alembic commands ###
