"""add_insurance_and_nsr_fields

Revision ID: a9edc3ac5047
Revises: c32f813bcdc5
Create Date: 2026-04-18 01:10:28.278701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy # ⚖️ Added for AI Vector Support

# revision identifiers, used by Alembic.
revision: str = 'a9edc3ac5047'
down_revision: Union[str, Sequence[str], None] = 'c32f813bcdc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ⚖️ Statutory Requirement: Enact the vector extension in the DB registry first
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospitals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('facility_code', sa.String(length=50), nullable=True),
    sa.Column('cac_number', sa.String(length=50), nullable=True),
    sa.Column('tin', sa.String(length=50), nullable=False),
    sa.Column('hospital_category', sa.String(length=20), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hospitals_facility_code'), 'hospitals', ['facility_code'], unique=True)
    op.create_index(op.f('ix_hospitals_public_id'), 'hospitals', ['public_id'], unique=True)
    
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('nin', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('blood_group', sa.String(length=5), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('data_processing_consent', sa.Boolean(), nullable=False),
    sa.Column('consent_timestamp', sa.DateTime(), nullable=True),
    sa.Column('nhia_id', sa.String(length=50), nullable=True),
    sa.Column('is_pregnant', sa.Boolean(), nullable=False),
    sa.Column('is_indigent', sa.Boolean(), nullable=False),
    sa.Column('nsr_id', sa.String(length=50), nullable=True),
    sa.Column('hmo_id', sa.String(length=50), nullable=True),
    sa.Column('hmo_provider_name', sa.String(length=100), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(nin) >= 11', name='min_nin_length'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nsr_id')
    )
    op.create_index(op.f('ix_patients_hmo_id'), 'patients', ['hmo_id'], unique=False)
    op.create_index(op.f('ix_patients_nin'), 'patients', ['nin'], unique=True)
    op.create_index(op.f('ix_patients_public_id'), 'patients', ['public_id'], unique=True)
    
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('nin', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nin')
    )
    op.create_index(op.f('ix_admins_email'), 'admins', ['email'], unique=True)
    
    op.create_table('doctors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('specialization', sa.String(length=100), nullable=False),
    sa.Column('license_number', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_doctors_license_number'), 'doctors', ['license_number'], unique=True)
    op.create_index(op.f('ix_doctors_specialization'), 'doctors', ['specialization'], unique=False)
    
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('target_nin', sa.String(length=20), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['doctors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    op.add_column('clinical_ledger', sa.Column('record_id', sa.Integer(), nullable=False))
    op.add_column('clinical_ledger', sa.Column('embedding', pgvector.sqlalchemy.VECTOR(dim=1536), nullable=True))
    op.alter_column('clinical_ledger', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    
    # Handling specific constraint cleanup
    op.create_foreign_key(None, 'clinical_ledger', 'medical_records', ['record_id'], ['id'])
    
    op.add_column('medical_records', sa.Column('diagnosis', sa.Text(), nullable=False))
    op.add_column('medical_records', sa.Column('clinical_data', sa.JSON(), nullable=False))
    op.add_column('medical_records', sa.Column('base_fee', sa.Float(), nullable=False))
    op.add_column('medical_records', sa.Column('flutterwave_ref', sa.String(length=100), nullable=True))
    op.add_column('medical_records', sa.Column('is_paid', sa.Boolean(), nullable=False))
    op.add_column('medical_records', sa.Column('fiscal_stamp', sa.String(length=100), nullable=True))
    
    op.create_index(op.f('ix_medical_records_timestamp'), 'medical_records', ['timestamp'], unique=False)
    op.create_unique_constraint(None, 'medical_records', ['flutterwave_ref'])
    op.create_unique_constraint(None, 'medical_records', ['fiscal_stamp'])
    op.create_foreign_key(None, 'medical_records', 'doctors', ['doctor_id'], ['id'])
    op.create_foreign_key(None, 'medical_records', 'hospitals', ['hospital_id'], ['id'])
    op.create_foreign_key(None, 'medical_records', 'patients', ['patient_nin'], ['nin'])
    
    # Note: Ensure clinical_notes column removal matches your previous schema state
    op.drop_column('medical_records', 'clinical_notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.add_column('medical_records', sa.Column('clinical_notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'medical_records', type_='foreignkey')
    op.drop_constraint(None, 'medical_records', type_='foreignkey')
    op.drop_constraint(None, 'medical_records', type_='foreignkey')
    op.drop_constraint(None, 'medical_records', type_='unique')
    op.drop_constraint(None, 'medical_records', type_='unique')
    op.drop_index(op.f('ix_medical_records_timestamp'), table_name='medical_records')
    op.drop_column('medical_records', 'fiscal_stamp')
    op.drop_column('medical_records', 'is_paid')
    op.drop_column('medical_records', 'flutterwave_ref')
    op.drop_column('medical_records', 'base_fee')
    op.drop_column('medical_records', 'clinical_data')
    op.drop_column('medical_records', 'diagnosis')
    op.drop_column('clinical_ledger', 'embedding')
    op.drop_column('clinical_ledger', 'record_id')
    op.drop_table('audit_logs')
    op.drop_table('doctors')
    op.drop_table('admins')
    op.drop_table('patients')
    op.drop_table('hospitals')
    op.execute('DROP EXTENSION IF EXISTS vector')